scrape_configs:
  - job_name: 'flask_app'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names: ['monitoring']
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        target_label: job
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        target_label: port