name: Push to DockerHub
on:
  push:
    branches:
        - qa
jobs:
  run_tests:
    uses: crawlic-stud/itmo-ict-clouds-labs-boysFromK34212/.github/workflows/tests-workflow.yml@main

  build:
    needs: run_tests 
    uses: crawlic-stud/itmo-ict-clouds-labs-boysFromK34212/.github/workflows/deploy-workflow.yml@main
    with:
      image-name: itmo-ict-cloud-lab4-qa
    secrets: inherit
