name: Import secrets from Hashicorp

on:
  workflow_call:
    inputs:
      secrets:
        required: true
        type: string

jobs:
  import-secrets:
    runs-on: [ubuntu-latest]
    steps:
      - name: Get Hashicorp access token
        id: hcp_token
        run: |
          echo token=$(curl --location "https://auth.idp.hashicorp.com/oauth2/token" \
            --header "Content-Type: application/x-www-form-urlencoded" \
            --data-urlencode "client_id=${{ secrets.HCP_CLIENT_ID }}" \
            --data-urlencode "client_secret=${{ secrets.HCP_CLIENT_SECRET }}" \
            --data-urlencode "grant_type=client_credentials" \
            --data-urlencode "audience=https://api.hashicorp.cloud" | jq -r .access_token) >> $GITHUB_OUTPUT
    
      - name: Use access token to get secrets
        id: hcp_secrets
        run: | 
          for item in $(echo "${{ inputs.secrets }}" | tr ',' '\n'); do
            echo "Processing secret: $item"

            echo $item=$(curl \
              --location "https://api.cloud.hashicorp.com/secrets/2023-06-13/organizations/${{ secrets.HCP_VAULT_PATH }}/open/${item}" \
              --request GET \
              --header "Authorization: Bearer ${{ steps.hcp_token.outputs.token }}") >> $GITHUB_OUTPUT
          done
          
        
      - name: Save secrets
        run: echo ${{ steps.hcp_secrets.outputs }}
