name: Import secrets from Hashicorp

on:
  workflow_call:


jobs:
  import-secrets:
    runs-on: [ubuntu-latest]
    steps:
      - name: Get Hashicorp access token
        id: hcp_token
        run: |
          curl --location "https://auth.idp.hashicorp.com/oauth2/token" \
            --header "Content-Type: application/x-www-form-urlencoded" \
            --data-urlencode "client_id=${{ secrets.HCP_CLIENT_ID }}" \
            --data-urlencode "client_secret=${{ secrets.HCP_CLIENT_SECRET }}" \
            --data-urlencode "grant_type=client_credentials" \
            --data-urlencode "audience=https://api.hashicorp.cloud" | jq -r .access_token
    
      - name: Use access token to get secrets
        run: | 
          curl \
            --location "https://api.cloud.hashicorp.com/secrets/2023-06-13/organizations/${{ secrets.HCP_VAULT_PATH }}" \
            --request GET \
            --header "Authorization: Bearer ${{ steps.hcp_token.outputs }}"
        
