name: Run tests before release

on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Change directory 
        run: cd labs/lab4
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest src/tests.py